### ISSUE TITLE
Create services

### ISSUE THREAD

**Issue by ghermans** [idevelopment/service_status#2]
When we create a new incident ticket we need to assign a service on this ticket.
This includes services like WWW, FTP, IMAP, POP3, SMTP

#### Add services (form & DB table)

Name | Type | Description
------------ | ------------- | -------------
service_name | text | The name of the service

**Comment by Tjoosten** [comment]
@ghermans Can u update the description?

**Comment by ghermans** [comment]
@Tjoosten description has been updated.
