### ISSUE TITLE
Create incidents controller. 

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/service_status#27]
What we need in the incidents controllers. For the following functions.

- Report incident.
- Search incident
- All incidents. 

#### DB overview table: 

Fields | Type | Description
------------ | ------------- | -------------
Subject | text | The subject regarding this incident, for example (Router maintenance)
Status | dropdown | Default status labels: Investigating, Confirmed, Resolved
Service(s) | dropdown (multiple) | Populate the services from the db #2, for example (WWW,FTP,SMTP,IMAP,POP3)
message | textarea | General information regarding the incident.

#### Updates: 

4929e98 add empty incidents controller
54c56eb add empty functions.

#### Notes: 
- All changes will be happen at the branch named `patch-27`
- @ghermans feel free to add things.

**Comment by ghermans** [comment]
@Tjoosten i just updated the tasks list.

**Comment by Tjoosten** [comment]
@ghermans That the db table right?

**Comment by Tjoosten** [comment]
related to #1 

i've created a view waiting to @ghermans to review my changers in the PR form `patch-27`

**Comment by ghermans** [comment]
@Tjoosten patch-27 is already merged, also your commit  "Fix #27 -> Add placeholder to abuse form" has  the wrong issue number -> it should be related to #29

**Comment by Tjoosten** [comment]
i know i've seen it
