### ISSUE TITLE
Add api   

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/service_status#34]
## Other
- [x] Create key mechanism.
- [x] Create view.
## Endpoints
- [ ] Get all incidents
- [ ] Get all open incidents
- [ ] Get all closed incidents
- [ ] Get assigned incidents

**Comment by Tjoosten** [comment]
@ghermans any idea for functionality or endpoints?

**Comment by ghermans** [comment]
- Get all incidents
- Get all open incidents
- Get all closed incidents
- Get assigned incidents
- Get unassigned incidents
